import axios from 'axios';

const api = axios.create({
  // Use the full URL generated by Railway for your NEW service
  baseURL: 'https://aware-mindfulness-production.up.railway.app', 
});

api.interceptors.request.use((config) => {
  const user = JSON.parse(localStorage.getItem('user'));
  if (user?.token) {
    config.headers.Authorization = `Bearer ${user.token}`;
  }
  return config;
});

export default api;
